server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://db-host:3306/legendme_auth_db?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: legendme-login-svc
    access-exp-minutes: 60

legendme-users-svc:
  url: https://localhost:8080/legendme/users/create/google-user
  findByEmailUrl: https://localhost:8080/legendme/users/by-email
  createLocalUrl: https://localhost:8080/legendme/users/create

logging:
  level:
    com.legendme.login.svc: INFO
    org.springframework: WARN