server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/legendme_auth_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:legendme_auth}
    password: ${DB_PASSWORD:StrongPassw0rd!}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: legendme-login-svc
    access-exp-minutes: 60

legendme-users-svc:
  url: http://localhost:8080/legendme/users/create/google-user
  findByEmailUrl: http://localhost:8080/legendme/users/by-email
  createLocalUrl: http://localhost:8080/legendme/users/create

logging:
  level:
    com.legendme.login.svc: INFO
    org.springframework.security: INFO